version: '3.8'

services:
  db:
    image: mysql:5.7.40
    container_name: mysql_db
    ports:
      - "3307:3306"  # 3306 à l'intérieur du conteneur exposé comme 3307 sur l'hôte
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mouvstockdb
    volumes:
      - app-data:/var/lib/mysql
    networks:
      - my-network

  mouvstock:
    build:
      context: ./mouvstock
      dockerfile: Dockerfile
    container_name: mouvstock
    ports:
      - "3000:3000"  # 3000 à l'intérieur du conteneur exposé comme 3000 sur l'hôte
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/mouvstockdb
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  app-data:
